### ISSUE TITLE
Will markless support table like GFM?

### ISSUE THREAD

**Issue by muyinliu** [Shirakumo/markless#1]
[GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) support table like this:

```
| field  | value  |
|--------|--------|
| field1 | value1 |
| field2 | value2 |
```

will be:

| field | value |
|-----|-----|
| field1 | value1 |
| field2 | value2 |

**Comment by Shinmera** [comment]
No. Tables in ASCII are a horrid mess, both to read, parse, and specify.
